
SOURCES := AssetManager.cpp World.cpp ScreenObject.cpp SpriteAnimation.cpp

HEADERS := exceptions.hpp entity.hpp AssetManager.hpp World.hpp ScreenObject.hpp FactoryFunction.hpp SpriteAnimation.hpp

SEARCH  := AI Assets Entities Physics World ..

RELATIVE := ..
include $(RELATIVE)/Makefile.native
