
SOURCES := AssetManager.cpp Editor.cpp World.cpp ScreenObject.cpp

HEADERS := exceptions.hpp Editor.hpp entity.hpp AssetManager.hpp World.hpp ScreenObject.hpp FactoryFunction.hpp

SEARCH  := AI Assets Editor Entities Physics World ..

RELATIVE := ..
include $(RELATIVE)/Makefile.native
