
SOURCES := AssetManager.cpp World.cpp ScreenObject.cpp player.cpp

HEADERS := exceptions.hpp entity.hpp AssetManager.hpp World.hpp ScreenObject.hpp FactoryFunction.hpp player.hpp

SEARCH  := AI Assets Entities Physics World ..

RELATIVE := ..
include $(RELATIVE)/Makefile.native
